# Generated by Django 2.2.3 on 2019-07-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='parsing URL')),
                ('handling_time', models.DateTimeField(verbose_name='handling time')),
            ],
        ),
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Parser.Request')),
                ('encoding', models.CharField(max_length=10, verbose_name='page encoding')),
                ('title', models.TextField(blank=True, verbose_name='page title')),
                ('h1', models.TextField(blank=True, verbose_name='<h1> tag')),
            ],
        ),
    ]
