# Generated by Django 2.2.3 on 2019-08-03 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseresult',
            name='encoding',
            field=models.CharField(blank=True, max_length=10, verbose_name='page encoding'),
        ),
        migrations.AlterField(
            model_name='request',
            name='handling_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='handling time'),
        ),
    ]
